// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-0eWdX6J5-CYfVBhX40o8hkdXq4pNxGY',
    appId: '1:116422890523:web:3dbe5c3cae5d956485d4be',
    messagingSenderId: '116422890523',
    projectId: 'scan-desc-1796e',
    authDomain: 'scan-desc-1796e.firebaseapp.com',
    storageBucket: 'scan-desc-1796e.firebasestorage.app',
    measurementId: 'G-Q6CEDYXG8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZAN_Jbb4jzVn1XXtPnRI7sYLQg6HgGE',
    appId: '1:116422890523:android:83c73c41110a56ba85d4be',
    messagingSenderId: '116422890523',
    projectId: 'scan-desc-1796e',
    storageBucket: 'scan-desc-1796e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixlOQP4t9ZlJKyV7eTH5LIZ39ArvisbE',
    appId: '1:116422890523:ios:5f63cd23bc4db3c885d4be',
    messagingSenderId: '116422890523',
    projectId: 'scan-desc-1796e',
    storageBucket: 'scan-desc-1796e.firebasestorage.app',
    iosBundleId: 'com.example.scanDesc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAixlOQP4t9ZlJKyV7eTH5LIZ39ArvisbE',
    appId: '1:116422890523:ios:5f63cd23bc4db3c885d4be',
    messagingSenderId: '116422890523',
    projectId: 'scan-desc-1796e',
    storageBucket: 'scan-desc-1796e.firebasestorage.app',
    iosBundleId: 'com.example.scanDesc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-0eWdX6J5-CYfVBhX40o8hkdXq4pNxGY',
    appId: '1:116422890523:web:758cce52432528c585d4be',
    messagingSenderId: '116422890523',
    projectId: 'scan-desc-1796e',
    authDomain: 'scan-desc-1796e.firebaseapp.com',
    storageBucket: 'scan-desc-1796e.firebasestorage.app',
    measurementId: 'G-5SR5E20C2G',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA-0eWdX6J5-CYfVBhX40o8hkdXq4pNxGY',
    appId: '1:116422890523:web:3dbe5c3cae5d956485d4be',
    messagingSenderId: '116422890523',
    projectId: 'scan-desc-1796e',
    authDomain: 'scan-desc-1796e.firebaseapp.com',
    storageBucket: 'scan-desc-1796e.firebasestorage.app',
    measurementId: 'G-Q6CEDYXG8W',
  );
}
